// Generated by CoffeeScript 1.12.3
(function() {
  var Random;

  module.exports = Random = (function() {
    Random.prototype.a = 16807;

    Random.prototype.m = 2147483647;

    Random.prototype.q = 127773;

    Random.prototype.r = 2836;

    function Random(seed) {
      this.seed = seed;
      if (this.seed == null) {
        while (true) {
          this.seed = new Date().getTime() % this.m;
          if (this.seed > 0 && this.seed < this.m) {
            break;
          }
        }
      }
    }

    Random.prototype.random = function() {
      var hi, lo, test;
      hi = Math.floor(this.seed / this.q);
      lo = this.seed % this.q;
      test = this.a * lo - this.r * hi;
      this.seed = test > 0 ? test : test + this.m;
      return this.seed;
    };

    Random.prototype.int = function(max) {
      var maxAllowed, rnd;
      maxAllowed = Math.floor(this.m / max) * max;
      while (true) {
        rnd = this.random();
        if (rnd < maxAllowed) {
          break;
        }
      }
      return rnd % max;
    };

    return Random;

  })();

}).call(this);
